require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


target 'ownyourdata' do  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # used as native module in file "RNLibSodium.m"
  pod 'libsodium', '~> 1.0'

  # Needed according to https://github.com/react-native-community/react-native-permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  # needed by qr code scanner
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  # IMPORTANT:
  # This method is needed for a libsodium patch
  # read more below
  def change_lines_in_file(file_path, &change)  
    contents = []
  
    file = File.open(file_path, 'r')
    file.each_line do | line |
      contents << line
    end
    file.close
  
    File.open(file_path, 'w') do |f|
      f.puts(change.call(contents))
    end
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)

    # This is a patch for libsodium
    # libsodium includes its header files by specifying the filename alone
    # This causes problems, as XCode tries to load header files from somewhere else
    # Therefore, this patch explicitly specifies "libsodium" as the source for header files

    # Many, many thanks to github user Jpunt, whom the idea is from patching this issue in the podfile
    # This is the lovely podfile he created -> https://gist.github.com/Jpunt/3fe75effd54a702034b75ff697e47578
    # Also here -> https://github.com/facebook/yoga/issues/711
    libsodiumDir = './Pods/libsodium/**/*.c'

    print "Patching libsodium in with glob '#{libsodiumDir}' ... "
    Dir.glob(libsodiumDir) do |filename|
      change_lines_in_file(filename) do |lines|
        lines.map { |line| 
          line.include?('#include "utils.h"') ? '#include "libsodium/utils.h"' : 
          line.include?('#include "core.h"') ? '#include "libsodium/core.h"' : line
        }
      end
    end
    print "successful\n"
  end
end